[package]
name = "cobb_totem"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
tree-sitter = "0.25.10"
tree-sitter-ocaml = "0.24.2"
clap = { version = "4.5", features = ["derive"] }

[features]
debug = []
